
ALTER TABLE BOARD
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_BOARD;

/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 게시판 */
CREATE TABLE BOARD (
	SEQ NUMBER NOT NULL, /* 순번 */
	TITLE VARCHAR2(1000 CHAR) NOT NULL, /* 제목 */
	CONTENTS CLOB, /* 내용 */
	READ_CNT NUMBER DEFAULT 0, /* 조회수 */
	DIV VARCHAR2(2 BYTE), /* 구분 */
	REG_ID VARCHAR2(12 BYTE), /* 등록자 */
	REG_DT DATE DEFAULT SYSDATE, /* 등록일 */
	MOD_ID VARCHAR2(12 BYTE), /* 수정자 */
	MOD_DT DATE DEFAULT SYSDATE /* 수정일 */
);

COMMENT ON TABLE BOARD IS '게시판';

COMMENT ON COLUMN BOARD.SEQ IS '순번';

COMMENT ON COLUMN BOARD.TITLE IS '제목';

COMMENT ON COLUMN BOARD.CONTENTS IS '내용';

COMMENT ON COLUMN BOARD.READ_CNT IS '조회수';

COMMENT ON COLUMN BOARD.DIV IS '구분';

COMMENT ON COLUMN BOARD.REG_ID IS '등록자';

COMMENT ON COLUMN BOARD.REG_DT IS '등록일';

COMMENT ON COLUMN BOARD.MOD_ID IS '수정자';

COMMENT ON COLUMN BOARD.MOD_DT IS '수정일';

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		SEQ ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			SEQ
		);


