--12C이후 부터 가능
--1. DEFAULT VALUE로 SEQUENCE의 NEXT VALUE지정 가능
--게시글번호 자동증가

--1.1. 시퀀스 생성
--1.2. 시퀀스를 이용한 테이블 PK생성

CREATE SEQUENCE t_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 20
NOCYCLE;

CREATE TABLE t_seq_test(
	no NUMBER DEFAULT t_seq.NEXTVAL PRIMARY KEY,
	name VARCHAR2(20)
);

DECLARE

BEGIN
	FOR i IN 1..10
	LOOP
		INSERT INTO t_seq_test(name) VALUES(DBMS_RANDOM.STRING('A',10)); --영문자 10자리
	END LOOP;
END;
/
--      NO NAME                
---------- --------------------
--       1 UIJjqXQiAB          
--       2 WlsUnBtfiH          
--       3 CoQqAUnDdf          
--       4 OUBqBQWPix          
--       5 eBRGVUKvVh          
--       6 WBItJUcxnU          
--       7 DeCBsYCPjW          
--       8 yXhzNYJbmW          
--       9 BJEmZYpdno          
--      10 katlzWaTVE          


--INVISIBLE_COLUMN

CREATE TABLE t_member(
	no NUMBER,
	name VARCHAR2(20),
	tel NUMBER,
	jumin VARCHAR2(13) INVISIBLE
);

INSERT INTO t_member
VALUES(1,'AAA','0123456789','123456-1234567');
--오류. INVISIBLE COLUMN에는 데이터를 입력할 수 없다.

--VISIBLE로 변경
ALTER TABLE t_member MODIFY (jumin VISIBLE);

--INVISIBLE로 변경
ALTER TABLE t_member MODIFY (jumin INVISIBLE);

--
SELECT table_name, column_name, hidden_column
FROM user_tab_cols
WHERE table_name = 'T_MEMBER'
;
--TABLE_NAME      COLUMN_NAME    HID
----------------- -------------- ---
--T_MEMBER        NO             NO 
--T_MEMBER        NAME           NO 
--T_MEMBER        TEL            NO 
--T_MEMBER        JUMIN          YES


--TOP_N
--출력을 원하는 특정 순위만큼의 데이터를 출력할 수 있다.

CREATE SEQUENCE t_seq2;

CREATE TABLE t_member2(
	no NUMBER DEFAULT t_seq2.NEXTVAL PRIMARY KEY,
	name VARCHAR2(20),
	tel NUMBER,
	jumin VARCHAR2(13)
);

INSERT INTO t_member2(name, tel, jujmin) 
VALUES('AAA','010-1234-5678','123456-1234567');

INSERT INTO t_member2(name, tel, jujmin) 
VALUES('BBB','010-1234-5678','123456-1234567');

INSERT INTO t_member2(name, tel, jujmin) 
VALUES('CCC','010-1234-5678','123456-1234567');

INSERT INTO t_member2(name, tel, jujmin) 
VALUES('DDD','010-1234-5678','123456-1234567');

INSERT INTO t_member2(name, tel, jujmin) 
VALUES('EEE','010-1234-5678','123456-1234567');

SELECT * 
FROM t_member2;
--
--      NO NAME                     TEL
---------- ---------------   ----------
--       3 AAA               1012345678
--       4 BBB               1022345678
--       5 CCC               1032345678
--       6 DDD               1042345678
--       7 EEE          	 1052345678

SELECT *
FROM t_member2
FETCH FIRST 3 ROWS ONLY;
--
--      NO NAME                     TEL
---------- ---------------   ----------
--       3 AAA               1012345678
--       4 BBB               1022345678
--       5 CCC               1032345678

--OFFSET 2 ROWS -> 처음 2줄은 건너 뛰시오
--FETCH FIRST 3 ROWS ONLY; -> 그 다음 3중을 출력하시오
SELECT *
FROM t_member2
OFFSET 2 ROWS
FETCH FIRST 3 ROWS ONLY;
--
--      NO NAME                     TEL
---------- ---------------   ----------
--       5 CCC               1032345678
--       6 DDD               1042345678
--       7 EEE               1052345678

--IDENTITY_COLUMN
--PRIMARY KEY를 자동으로 생성
--시퀀스 속성을 설정 가능(EX.START WITH 10 INCREMENT BY 3)

CREATE TABLE t_iden(
	no NUMBER GENERATED BY DEFAULT
		AS IDENTITY (START WITH 10 INCREMENT BY 3),
	name VARCHAR2(320)
); 

INSERT INTO t_iden(name) VALUES('aaa');
INSERT INTO t_iden(name) VALUES('bbb');
INSERT INTO t_iden(name) VALUES('ccc');
--
--      NO NAME                                                                                                                                                                                                                                                                                                                            
---------- ---------------
--      10 aaa                                                                                                                                                                                                                                                                                                                             
--      13 bbb                                                                                                                                                                                                                                                                                                                             
--      16 CCC    

--NULL값을_위한_DEFAULT 

--일반적인 default
--입력된 값이 없을 경우 디폴트로 지정한 값이 자동으로 들어감
CREATE TABLE d_test100(
	no NUMBER,
	name VARCHAR2(200),
	sal NUMBER DEFAULT 200
);

INSERT INTO d_test100(no, name) VALUES(1,'AAA');
INSERT INTO d_test100 VALUES(1,'BBB', NULL);
--   NO NAME               SAL
---------- ----------- ----------
--       1 AAA                200
--       2 BBB                   


--개선된 default
--입력된 값이 없을 경우와 NULL값이 입력 되었을 때 100이 들어감
CREATE TABLE d_test200(
	no NUMBER,
	name VARCHAR2(200),
	sal NUMBER DEFAULT ON NULL 100
); 














































