--권한관리
--1. 관리자 계정으로 접근
--2. 테이블 스페이스 생성: SPRING_TS.DBF
--3. 사용자 생성: SPRING/eclass
--4. 권한 할당
--5. 접속해서 테이블 생성

--tablespace 위치 확인
COL tablespace_name FOR A10
COL file_name FOR A50
SELECT tablespace_name, file_name
FROM dba_data_files;
--
--TABLESPACE FILE_NAME
------------ --------------------------------------------------
--USERS      C:\APP\APP\ORACLE\ORADATA\XE\USERS.DBF
--SYSAUX     C:\APP\APP\ORACLE\ORADATA\XE\SYSAUX.DBF
--UNDOTBS1   C:\APP\APP\ORACLE\ORADATA\XE\UNDOTBS1.DBF
--SYSTEM     C:\APP\APP\ORACLE\ORADATA\XE\SYSTEM.DBF

--tablespace 생성
CREATE TABLESPACE SPRING_TS
datafile 'C:\APP\APP\ORACLE\ORADATA\XE\SPRING_TS.DBF'
size 300M AUTOEXTEND ON NEXT 30M;
--
--Tablespace created.
--
--TABLESPACE FILE_NAME
------------ --------------------------------------------------
--USERS      C:\APP\APP\ORACLE\ORADATA\XE\USERS.DBF
--SYSAUX     C:\APP\APP\ORACLE\ORADATA\XE\SYSAUX.DBF
--UNDOTBS1   C:\APP\APP\ORACLE\ORADATA\XE\UNDOTBS1.DBF
--SYSTEM     C:\APP\APP\ORACLE\ORADATA\XE\SYSTEM.DBF
--★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
--SPRING_TS  C:\APP\APP\ORACLE\ORADATA\XE\SPRING_TS.DBF
--★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

--계정생성
--12c 이후 버전은 계정 생성시 C##를 넣어야 함
--이를 피하기 위해 아래의 코드를 입력함
ALTER SESSION SET "_oracle_script"=true;

CREATE USER SPRING IDENTIFIED BY eclass
DEFAULT TABLESPACE SPRING_TS
TEMPORARY TABLESPACE TEMP;
--
--User created.

--권한부여
GRANT dba TO SPRING;
--
--Grant succeeded.

------------------------------------------------------------

--원격접속, 클라우드를 쓸 경우
tnsname.ora
XE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = SERVER_IP)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )
LISTENER_XE =
  (ADDRESS = (PROTOCOL = TCP)(HOST = SERVER_IP)(PORT = 1521))
ORACLR_CONNECTION_DATA =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
    (CONNECT_DATA =
      (SID = CLRExtProc)
      (PRESENTATION = RO)
    )
  )

listener.ora  
# listener.ora Network Configuration File: C:\app\sist\product\18.0.0\dbhomeXE\NETWORK\ADMIN\listener.ora
# Generated by Oracle configuration tools.
DEFAULT_SERVICE_LISTENER = XE
SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (SID_NAME = CLRExtProc)
      (ORACLE_HOME = C:\app\sist\product\18.0.0\dbhomeXE)
      (PROGRAM = extproc)
      (ENVS = "EXTPROC_DLLS=ONLY:C:\app\sist\product\18.0.0\dbhomeXE\bin\oraclr18.dll")
    )
  )
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 211.238.142.124)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )




























